//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBackOutBill
    {
        public int BackOutBillID { get; set; }
        public Nullable<int> BackoutID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string OutProdNum { get; set; }
        public string OutPrice { get; set; }
        public string OutTotal { get; set; }
    
        public virtual TblBackOut TblBackOut { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
