//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBackIn
    {
        public TblBackIn()
        {
            this.TblBackInBills = new HashSet<TblBackInBill>();
        }
    
        public int BackInID { get; set; }
        public Nullable<System.DateTime> DateOfBackeIn { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string TotalPaybake { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual TblStore TblStore { get; set; }
        public virtual TblUser TblUser { get; set; }
        public virtual ICollection<TblBackInBill> TblBackInBills { get; set; }
    }
}
