//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCusPro
    {
        public int ReporttID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> DateOfProc { get; set; }
        public string PayedValue { get; set; }
        public string ProcName { get; set; }
    
        public virtual TblCustomer TblCustomer { get; set; }
    }
}
