//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCustomer
    {
        public TblCustomer()
        {
            this.TblCusPros = new HashSet<TblCusPro>();
            this.TblRepaySales = new HashSet<TblRepaySale>();
            this.TblSaleBills = new HashSet<TblSaleBill>();
        }
    
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerCompany { get; set; }
        public string Credit { get; set; }
        public string Debit { get; set; }
    
        public virtual ICollection<TblCusPro> TblCusPros { get; set; }
        public virtual ICollection<TblRepaySale> TblRepaySales { get; set; }
        public virtual ICollection<TblSaleBill> TblSaleBills { get; set; }
    }
}
