//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductType
    {
        public TblProductType()
        {
            this.TblProducts = new HashSet<TblProduct>();
            this.TblPurchases = new HashSet<TblPurchas>();
            this.TblSales = new HashSet<TblSale>();
        }
    
        public int ProductTypeID { get; set; }
        public string ProductType { get; set; }
    
        public virtual ICollection<TblProduct> TblProducts { get; set; }
        public virtual ICollection<TblPurchas> TblPurchases { get; set; }
        public virtual ICollection<TblSale> TblSales { get; set; }
    }
}
