//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProvider
    {
        public TblProvider()
        {
            this.TblBackOuts = new HashSet<TblBackOut>();
            this.TblBills = new HashSet<TblBill>();
            this.TblNoteBooks = new HashSet<TblNoteBook>();
            this.TblProProcs = new HashSet<TblProProc>();
        }
    
        public int ProviderID { get; set; }
        public string ProviderName { get; set; }
        public string TelephoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string Credit { get; set; }
        public string Debit { get; set; }
    
        public virtual ICollection<TblBackOut> TblBackOuts { get; set; }
        public virtual ICollection<TblBill> TblBills { get; set; }
        public virtual ICollection<TblNoteBook> TblNoteBooks { get; set; }
        public virtual ICollection<TblProProc> TblProProcs { get; set; }
    }
}
