//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStorage
    {
        public TblStorage()
        {
            this.TblExpenses = new HashSet<TblExpens>();
            this.TblIncomes = new HashSet<TblIncome>();
            this.TblProcedures = new HashSet<TblProcedure>();
            this.TblRepayDebts = new HashSet<TblRepayDebt>();
            this.TblRepaySales = new HashSet<TblRepaySale>();
            this.TblStorageProces = new HashSet<TblStorageProce>();
        }
    
        public int StorageID { get; set; }
        public string StorageName { get; set; }
        public string TotalMoney { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual ICollection<TblExpens> TblExpenses { get; set; }
        public virtual ICollection<TblIncome> TblIncomes { get; set; }
        public virtual ICollection<TblProcedure> TblProcedures { get; set; }
        public virtual ICollection<TblRepayDebt> TblRepayDebts { get; set; }
        public virtual ICollection<TblRepaySale> TblRepaySales { get; set; }
        public virtual ICollection<TblStorageProce> TblStorageProces { get; set; }
        public virtual TblStore TblStore { get; set; }
    }
}
