//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int ProcedureID { get; set; }
        public Nullable<int> SaleBillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string BTotal { get; set; }
        public string SNotes { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblProductType TblProductType { get; set; }
        public virtual TblSaleBill TblSaleBill { get; set; }
    }
}
