//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStorageProce
    {
        public int SProcID { get; set; }
        public Nullable<int> SActionID { get; set; }
        public Nullable<System.DateTime> SPDate { get; set; }
        public string SPMoney { get; set; }
        public Nullable<int> StorageID { get; set; }
    
        public virtual TblStorageAction TblStorageAction { get; set; }
        public virtual TblStorage TblStorage { get; set; }
    }
}
