//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStorageAction
    {
        public TblStorageAction()
        {
            this.TblStorageProces = new HashSet<TblStorageProce>();
        }
    
        public int SActionID { get; set; }
        public string SActionName { get; set; }
    
        public virtual ICollection<TblStorageProce> TblStorageProces { get; set; }
    }
}
