//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTransfer
    {
        public int TransferID { get; set; }
        public Nullable<int> TransferBillID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string TransQuantity { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblTransferBill TblTransferBill { get; set; }
    }
}
