//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I_Count
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTemporary
    {
        public int TempID { get; set; }
        public string TProType { get; set; }
        public string TproName { get; set; }
        public string TPrice { get; set; }
        public string TQuantity { get; set; }
        public string TTotal { get; set; }
        public string TSPrise1 { get; set; }
        public string TSPrice { get; set; }
        public string TID { get; set; }
        public Nullable<int> TemporaryID { get; set; }
        public string TExsist { get; set; }
        public string SNote { get; set; }
        public string SEarn { get; set; }
    
        public virtual TblTemporaryType TblTemporaryType { get; set; }
    }
}
